WordPress/phpunit-test-runner

README.md

It's more helpful to first indicate that `.env.default` should be copied, so the user can use it to keep track of details.

Clarify local vs. remote for readability

---

.env.default
test.php

Pantheon doesn't permit calling `ssh [...] php phpunit.phar` directly,
so the command execution needs to be proxied through a WP-CLI command.

Permit PHPUnit command execution to be configurable

---

functions.php

When a dataprovider is used phpunit produces an extra nested testsuite that looks like this: 
```XML
<testsuites>
<testsuite name="" tests="562" assertions="1883" failures="105" errors="21" time="21.991066">
<testsuite name="Tests_Canonical" file="/home/public/test/tests/phpunit/tests/canonical.php" tests="54" assertions="66" failures="0" errors="0" time="1.144615">
<testsuite name="Tests_Canonical::test_canonical" tests="54" assertions="66" failures="0" errors="0" time="1.144615">
<testcase name="test_canonical with data set #0" assertions="1" time="0.020822"/>
```
Instead of: 
```XML
<testsuites>
<testsuite name="" tests="562" assertions="1883" failures="105" errors="21" time="21.991066">
<testsuite name="Tests_Query_VerbosePageRules" …
```

Capture errors and total test time. 

---

cleanup.php
functions.php
prepare.php
report.php
test.php

If they're set but empty, we can assume the user forgot to comment them
out

Only use SSH connection details when non-empty

---

prepare.php

This PR uses the PHP executable specified in the `WPT_PHP_EXECUTABLE` to run the unit tests. This then allows the tests to be run on systems where multiple PHP versions have been installed but may not necessarily be the system default.

Update prepare.php to use the specified PHP executable for testing

---

report.php

As RHEL / CentOS 7 ship with Git 1.8.x, the current syntax doesn't correctly run on these systems. I've updated the args to be compatible with the older versions, however they haven't been tested on newer versions yet.

Modify git args to be compatible with older versions

---

README.md

- Updates the readme file to note that the test environment must be run on a non-root user, along with reasoning.
- Shortens the previous line's wording to match.
See: https://core.trac.wordpress.org/ticket/44233#comment:34 and https://wordpress.slack.com/archives/C3D6T7F8Q/p1555339715052200

Update README.md to note non-root user necessary

---

prepare.php

Changes the string that is replaced in `wp-tests-config.php` to account
for https://core.trac.wordpress.org/changeset/47122.
See: WordPress/phpunit-test-runner#105

Fix Environment Information Reporting

---

.env.default
prepare.php
report.php

I had problems with travis and the verbose mode of `rsync`:
> The job exceeded the maximum log length, and has been terminated.
I would suggest to remove the flag, or at least to hide it behind an `env` var.

remove verbose mode for rsync

---

prepare.php

The build process has already run, so we don't need the source libraries.

Also exclude `node_modules/` from rsync

---

prepare.php

I ran into issues with the test runner building on a system where global Grunt was not available.
This seems to work around the issue, and uses the locally installed Grunt after `npm install`.
Are there any drawbacks to doing it this way?

Use local Grunt, rather than relying on global.

---

prepare.php
test.php

The changes include:
- Downloads Composer PHAR to prepare directory when it is not available
- Checks test environment PHP version, and runs Composer to download PHPUnit on prepare environment with PHP < 7.1.
- Uses installed PHPUnit from Composer on test environment for PHP 7.1+
~This is a rough first pass. Putting here so folks can use it as a starting point.~
~I'm getting a segfault during tests on my installed version of PHP8, but it might be because it's PHP 8 RC1, and I need to update it.~ (Fixed)
~TODO: Install/download Composer so that it isn't necessary to be installed globally on the prepare environment.~ (Done)
See: #121

Install and use PHPUnit via composer.

---

functions.php
prepare.php

Fixes #65
This removes the `imagemagick` reporting under `system_utils` as the Package information isn't actually needed.
`imagick` php_module is already reported earlier in the same array. `convert` isn't always present on systems since the imagemagick package might not be installed along the php_module.

Remove shell exec convert

---

.github/workflows/tests.yml

@desrosj `never()` seems to cause a lot if issues, so I changed it to `${{ false }}`.
See: https://github.com/WordPress/phpunit-test-runner/actions

Skip action for this repo: use `${{ false }}` instead of `never()`

---

prepare.php

the `// ** MySQL settings ** //` string in the `wp-tests-config-sample.php` was changed lately so the runner might not work any more.
https://github.com/WordPress/wordpress-develop/commit/e860dee7274af6066b473bc37d031e8b3ced398f

fix search/replace issue

---

.github/workflows/tests.yml

If the reporting fails, the webspace will not be cleaned and that might cause side effects on the next run.

cleanup tests even if reporting fails

---

test.php

Risky tests cause "Failed" statuses on the "Hosting Tests results" page.
As these don't provide insight into the functionality of WordPress,
they should not be reported by default.
If the reporting of risky tests is desired, a `WPT_PHPUNIT_CMD` value can
be set in `.env`.
Resolves #167.

Add `--dont-report-useless-tests` flag by default.

---

functions.php
prepare.php

The test suite doesn't appear to use gs, so remove it from the metadata.
Apologies for 3 merge conflicting prs but it was the logical separation of changes.

remove gs --version

---

.travis.yml
README.md

This PR is a follow-up to #174, specifically to [this comment](https://github.com/WordPress/phpunit-test-runner/issues/174#issuecomment-1181607336), requesting that the test runner use Node 14 on its own.
1. In `.travis.yml` the `node_js` setting specifies `node`, [which is the latest stable release](https://docs.travis-ci.com/user/languages/javascript-with-nodejs/#specifying-nodejs-versions). However, the project's `package.json` is configured for Node 14, and to avoid compile errors under other versions, this has been changed to specifically use version `14`.
2. Following a Hosting Handbook [tests documentation update related to this requirement](https://github.com/WordPress/hosting-handbook/commit/91663bfd3672b9721bc40402bdefd4bb50c900f7), the README file now also indicates the need …

Update Travis CI to Use Node 14

---

functions.php
prepare.php

Addresses https://github.com/WordPress/phpunit-test-runner/issues/131.

Environment: check GD and Imagick availability & supported formats.

---

functions.php
prepare.php

There is a chance the curl executable could be of different version than the libcurl used by php.
Include the curl library version, the openssl version and zlib version.
This is less than curl --version of the form:
curl 7.82.0 (x86_64-redhat-linux-gnu) libcurl/7.82.0 OpenSSL/3.0.5 zlib/1.2.11 brotli/1.0.9 libidn2/2.3.3 libpsl/0.21.1 (+libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.46.0 OpenLDAP/2.6.2
Apologies as my php programming isn't the strongest.

Use curl information from library rather than curl --version

---

functions.php

Occasionally the requests to wp.org get rate limited.
After a discussion with the systems team, it was determined that the requests are being sent with a user agent, and are more likely to be blocked without one - this commit adds one.

Add UA to curl request

---

.github/workflows/tests.yml
.travis.yml
.vscode/settings.json

See: https://github.com/WordPress/phpunit-test-runner

updated Node version to latest supported one

---

.github/workflows/props-bot.yml

Props Bot is a GitHub Action that processes the activity on a pull request and any linked issues.
The bot attempts to associate each GitHub use account with a linked w.org one and outputs a formatted list of `Co-authored-by` trailers that can be copied and pasted into the merge commit message.
This ensures that everyone who contributed to a given merge receives props for their effort, and that the list of contributors is predictably formatted for easy processing.
This bot is currently in the following repositories under the WordPress organization:
- https://github.com/WordPress/wordpress-develop
- https://github.com/WordPress/gutenberg
- https://github.com/WordPress/plugin-check
- https://github.com/WordPress/performance
- https://github.com/WordPress/grunt-patch-wordpress
More details …

Introduce Props Bot workflow for consistent contributor attribution

---

prepare.php

Without it uses the hardcode `php` call.
However, we have 
`$WPT_PHP_EXECUTABLE = trim( getenv( 'WPT_PHP_EXECUTABLE' ) ) ? : 'php';`
for a reason
In our case, without this patch all works but the reporting/uploading bit:
`cd '/home/REDACTED/tmp' && php composer.phar config platform.php '8.2.28'
______
/ ____/___  ____ ___  ____  ____  ________  _____
/ /   / __ \/ __ `__ \/ __ \/ __ \/ ___/ _ \/ ___/
/ /___/ /_/ / / / / / / /_/ / /_/ (__  )  __/ /
\____/\____/_/ /_/ /_/ .___/\____/____/\___/_/
/_/
Composer version 2.8.9 2025-05-13 14:01:37
Usage:
command [options] [arguments]
Options:
-h, --help                     Display help for the given command. When no command is given display help for the list command
-q, --quiet                    Do not output any message
-V, --version …

[TASK] Use WPT_PHP_EXECUTABLE for composer

---

.gitignore

This adds several patterns to the `.gitignore` file to prevent accidentally committing files related to contributing through version control.
The `wp-test-runner` directory is also being added as the default directory for running tests locally.

Expand the .gitignore file

---

functions.php
prepare.php

- Remove dead code related to WPT_CERTIFICATE_VALIDATION in prepare.php
- Remove WPT_CERTIFICATE_VALIDATION processing from setup_runner_env_vars()
- Update PHPDoc to reflect removed functionality
- Fixes issue #265 where environment variable was processed but never used

Remove unused WPT_CERTIFICATE_VALIDATION environment variable
